### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ASSTOLF0** [ikno-the-box-guy/NamemcScraper#1]
Unhandled Exception: System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 104
Current browser version is 100.0.4896.62 with binary path C:\Users\xxx\AppData\Local\Chromium\Application\chrome.exe (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at Average_Skin_Generator.Program.Main() in C:\Users\xxx\Documents\GitHub\NamemcScraper\NamemcScraper\Average Skin Generator\Program.cs:line 33

**Comment by jlc893** [comment]
Your ChromeDriver is incompatible with your current Chrome browser. I'd suggest downloading the correct chromedriver [here](https://sites.google.com/chromium.org/driver/home). And make sure the path leads to the new ChromeDriver.

**Comment by ASSTOLF0** [comment]
Thanks for helping, works fine now
